CREATE TABLE IF NOT EXISTS `Install_Data` (
 `Installed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `User_Data` (
 `User_Id` INT AUTO_INCREMENT NOT NULL,
 `User_Type` INT NOT NULL,
 `User_FullName` VARCHAR(120) NOT NULL,
 `User_Email` VARCHAR(255) NOT NULL,
 `Create_by` INT NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Email`),
 PRIMARY KEY(`User_Id`)
);
CREATE TABLE IF NOT EXISTS `User_Token` (
 `User_Id` INT NOT NULL,
 `User_Token` CHAR(4) NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Id`, `User_Token`),
 FOREIGN KEY(`User_Id`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `User_Sessions` (
 `User_Id` INT NOT NULL,
 `Session_Token` CHAR(32) NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Id`, `Session_Token`),
 FOREIGN KEY(`User_Id`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `Careers` (
 `Career_Id` INT AUTO_INCREMENT NOT NULL,
 `Career_Name` VARCHAR(250) NOT NULL,
 `Create_by` INT NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(`Career_Id`),
 UNIQUE KEY(`Career_Name`),
 FOREIGN KEY(`Create_by`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `Careers_Years` (
 `Career_Id` INT NOT NULL,
 `Career_Year` INT NOT NULL,
 `Create_by` INT NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`Career_Id`, `Career_Year`),
 FOREIGN KEY(`Create_by`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY(`Career_Id`) REFERENCES `Careers`(`Career_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `Lessons` (
 `Lesson_Id` INT AUTO_INCREMENT NOT NULL,
 `Lesson_Name` VARCHAR(250) NOT NULL,
 `Create_by` INT NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`Lesson_Name`),
 PRIMARY KEY(`Lesson_Id`),
 FOREIGN KEY(`Create_by`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `Calendar` (
 `Calendar_Id` INT AUTO_INCREMENT NOT NULL,
 `Create_by` INT NOT NULL,
 `Career_Id` INT NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 `Observations` TINYTEXT NOT NULL,
 PRIMARY KEY(`Calendar_Id`),
 FOREIGN KEY(`Create_by`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY(`Career_Id`) REFERENCES `Careers`(`Career_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `Calendar_Data` (
 `Calendar_Id` INT NOT NULL,
 `Lesson_Id` INT NOT NULL,
 `Block_Id` INT NOT NULL,
 `Do_Date` DATE NOT NULL,
 `Reprogramming_Date` DATE NOT NULL,
 `Special_Date` DATE NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`Lesson_Id`, `Block_Id`, `Do_Date`, `Reprogramming_Date`, `Special_Date`),
 FOREIGN KEY(`Calendar_Id`) REFERENCES `Calendar`(`Calendar_Id`) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY(`Lesson_Id`) REFERENCES `Lessons`(`Lesson_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);